[profile.default]
src = "contracts/src"
out = "contracts/out"
libs = ["lib"]
solc = "0.8.24"

remappings = [
    "v4-core/=lib/v4-core/",
    "v4-periphery/=lib/v4-periphery/",
    "@openzeppelin/=lib/openzeppelin-contracts/"
]

[profile.default.optimizer]
enabled = true
runs = 200
